services:
  #PHP Service
  php:
    build: .
    environment:
      APP_ENV: ${App_ENV}
      CONTAINER_ROLE: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: database-admin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - '8081:80'
    depends_on:
      - database
      
volumes:
  db-data: ~